android.aapt2.disableDaemon=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx1g -Xms256m -Dfile.encoding=UTF-8 -Dcom.android.build.gradle.internal.aapt.Aapt2Daemon=false

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
